# Istio ingress gateways are not injected with the istio sidecar.
apiVersion: v1
kind: Namespace 
metadata:
  name: tenant1-ingress
  labels:
    tenant: tenant1        
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Equal", "value": "ingress", "effect": "NoSchedule", "key": "usage"}]'
---