output "result" {
  description = "The value generated by the private endpoint module."
  value       = azurerm_private_endpoint.privateEndpoint
}

output "endpoint_ip" {
  description = "Private IP allocated to the blob private endpoint."
  value       = azurerm_private_endpoint.privateEndpoint.private_service_connection.0.private_ip_address
}